# -*- coding: utf-8 -*-
"""
Algorithm Quality Gates & Governance Engine (ALCM Phase 2).

Provides industrial-grade quantitative quality gates:
1. LookaheadGuard: AST static analysis & dynamic temporal perturbation probe
   to prevent future data leakage (Lookahead Bias).
2. AShareComplianceGuard: Validates A-share trading rules (T+1 settlement,
   limit-up/down non-fillable orders, suspension/zero-liquidity execution).
3. OverfittingGuard: Out-of-Sample (OOS) performance decay verification and
   Marcos López de Prado's Deflated Sharpe Ratio (DSR).
4. AlgorithmQualityGate: Composite evaluation gate orchestrator with
   structured pass/warning/block governance reporting.
"""
from __future__ import annotations

import ast
import inspect
import math
import statistics
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Callable, Dict, List, Optional, Tuple, Union

from core.config import get_logger

logger = get_logger("core.models.quality_gates")


class QualityGateStatus(str, Enum):
    """Quality gate decision status."""
    PASSED = "passed"      # Compliant with all hard gates & statistical baselines
    WARNING = "warning"    # Minor deviations or near-boundary metrics (advisory review)
    BLOCKED = "blocked"    # Hard gate violation (lookahead leakage, illegal trades, severe overfitting)


@dataclass
class QualityGateReport:
    """Structured compliance and validation report generated by Quality Gates."""
    target_name: str
    status: QualityGateStatus
    score: float                         # Composite governance score (0 - 100)
    passed_checks: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    violations: List[str] = field(default_factory=list)
    metrics: Dict[str, Any] = field(default_factory=dict)
    recommendations: List[str] = field(default_factory=list)

    def is_passed(self) -> bool:
        return self.status == QualityGateStatus.PASSED

    def to_dict(self) -> Dict[str, Any]:
        return {
            "target_name": self.target_name,
            "status": self.status.value,
            "score": round(self.score, 2),
            "passed_checks": list(self.passed_checks),
            "warnings": list(self.warnings),
            "violations": list(self.violations),
            "metrics": dict(self.metrics),
            "recommendations": list(self.recommendations),
        }


# ==============================================================================
# G1.1: 无未来函数审查器 (LookaheadGuard)
# ==============================================================================
class LookaheadGuard:
    """
    Lookahead Bias & Future Leakage Guard.

    Combines:
    1. Static AST scan: detects forward slicing patterns (e.g., `i+1:`, `shift(-1)`).
    2. Dynamic Temporal Perturbation Probe: modifies future K-lines (t+1..T) and
       verifies whether the output at time `t` remains invariant.
    """

    @classmethod
    def audit_source_code(cls, func_or_class_or_code: Union[str, Any]) -> Tuple[bool, List[str]]:
        """
        Static AST code audit for obvious forward index lookaheads.
        Accepts function, class, or source code string.
        Returns: (is_clean, violations)
        """
        import textwrap
        violations = []

        if isinstance(func_or_class_or_code, str):
            source = textwrap.dedent(func_or_class_or_code)
        else:
            try:
                raw_src = inspect.getsource(func_or_class_or_code)
                source = textwrap.dedent(raw_src)
            except (TypeError, OSError):
                return True, ["Source code unavailable for dynamic introspection (built-in or C-extension)"]

        # Parse AST
        try:
            tree = ast.parse(source)
        except SyntaxError as e:
            return False, [f"AST parsing failed: {e}"]

        for node in ast.walk(tree):
            # Check for forward slice lower index like [idx + 1:] or [i+1]
            if isinstance(node, ast.Slice):
                if isinstance(node.lower, ast.BinOp) and isinstance(node.lower.op, ast.Add):
                    if isinstance(node.lower.right, ast.Constant) and isinstance(node.lower.right.value, (int, float)):
                        if node.lower.right.value > 0:
                            violations.append(
                                f"Suspicious forward slice offset detected: lower bound +{node.lower.right.value}"
                            )

            # Check for shift(-k)
            if isinstance(node, ast.Call):
                if isinstance(node.func, ast.Attribute) and node.func.attr == "shift":
                    for arg in node.args:
                        if isinstance(arg, ast.UnaryOp) and isinstance(arg.op, ast.USub):
                            violations.append("Pandas backward shift(-k) detected without forward alignment")

        is_clean = len(violations) == 0
        return is_clean, violations

    @classmethod
    def probe_temporal_integrity(
        cls,
        func: Callable[..., Any],
        sample_klines: List[Any],
        bar_index: Optional[int] = None,
        *args: Any,
        **kwargs: Any,
    ) -> Tuple[bool, str]:
        """
        Dynamic Temporal Perturbation Probe.

        Tests whether the output at target index `bar_index` changes when
        subsequent future data (idx+1..end) is heavily perturbed.
        """
        if not sample_klines or len(sample_klines) < 10:
            return True, "Insufficient sample K-lines for dynamic perturbation"

        t = bar_index if bar_index is not None else len(sample_klines) // 2
        t = max(2, min(t, len(sample_klines) - 2))

        # Deep copy original sequence
        import copy
        k_original = copy.deepcopy(sample_klines)
        k_perturbed = copy.deepcopy(sample_klines)

        # Apply extreme perturbation to all bars AFTER index t
        for i in range(t + 1, len(k_perturbed)):
            bar = k_perturbed[i]
            if isinstance(bar, list):
                # Format: [date, open, close, high, low, volume, ...]
                bar[1] = float(bar[1]) * 10.0
                bar[2] = float(bar[2]) * 10.0
                bar[3] = float(bar[3]) * 10.0
                bar[4] = float(bar[4]) * 10.0
                if len(bar) > 5:
                    bar[5] = float(bar[5]) * 100.0
            elif isinstance(bar, dict):
                bar["open"] = float(bar.get("open", 10.0)) * 10.0
                bar["close"] = float(bar.get("close", 10.0)) * 10.0
                bar["high"] = float(bar.get("high", 10.0)) * 10.0
                bar["low"] = float(bar.get("low", 10.0)) * 10.0
                bar["volume"] = float(bar.get("volume", 1000.0)) * 100.0

        # Execute on both original and perturbed sequence
        try:
            # Check if func accepts idx parameter
            sig = inspect.signature(func)
            if "idx" in sig.parameters:
                kwargs_t = dict(kwargs)
                kwargs_t["idx"] = t
                out_orig = func(k_original, *args, **kwargs_t)
                out_pert = func(k_perturbed, *args, **kwargs_t)
            else:
                # Sliced invocation up to t
                out_orig = func(k_original[: t + 1], *args, **kwargs)
                out_pert = func(k_perturbed[: t + 1], *args, **kwargs)

            # Compare outputs
            if out_orig != out_pert:
                return False, f"Output at bar {t} changed after future data perturbation (Lookahead Bias Detected!)"

            return True, f"Passed temporal perturbation probe at bar {t}"
        except Exception as exc:
            return False, f"Dynamic probe execution error: {exc}"


# ==============================================================================
# G1.2: A股交易制度合规审查器 (AShareComplianceGuard)
# ==============================================================================
class AShareComplianceGuard:
    """
    A-Share Market Rule & Regulatory Compliance Guard.

    Validates:
    1. T+1 Settlement Rule: intraday buy-then-sell without prior overnight positions.
    2. Limit-up/Limit-down Matching: orders cannot fill on unyielding one-word limit boards.
    3. Trading Suspensions: zero volume / halted stock execution rejection.
    """

    @classmethod
    def audit_trade_log(
        cls,
        trades: List[Dict[str, Any]],
        klines_by_date: Optional[Dict[str, Dict[str, float]]] = None,
    ) -> Tuple[bool, List[str]]:
        """
        Audit a sequence of simulated trades against A-share rules.
        Returns: (is_compliant, violations)
        """
        violations = []
        if not trades:
            return True, []

        # 1. T+1 Rule validation
        positions: Dict[str, Dict[str, Any]] = {}
        # Track buy positions with timestamps/dates
        for trade in trades:
            code = trade.get("code", trade.get("symbol", "DEFAULT"))
            action = trade.get("action", "").lower()
            t_date = trade.get("date", "")
            qty = trade.get("qty", trade.get("shares", trade.get("volume", 0)))

            if code not in positions:
                positions[code] = {"available": 0, "frozen": 0, "last_buy_date": None}

            pos = positions[code]

            # Overnight rollover if date advanced
            if pos["last_buy_date"] and pos["last_buy_date"] != t_date:
                pos["available"] += pos["frozen"]
                pos["frozen"] = 0

            if action == "buy":
                pos["frozen"] += qty
                pos["last_buy_date"] = t_date
            elif action == "sell":
                if pos["available"] < qty:
                    # Illegal intraday sale without prior settled shares
                    violations.append(
                        f"T+1 Violation on {t_date} for {code}: attempted to sell {qty} shares, "
                        f"but only {pos['available']} were settled overnight (frozen intraday: {pos['frozen']})."
                    )
                else:
                    pos["available"] -= qty

            # 2. Limit price & Suspension checks if market context provided
            if klines_by_date and t_date in klines_by_date:
                k = klines_by_date[t_date]
                op = float(k.get("open", 0.0))
                cl = float(k.get("close", 0.0))
                hi = float(k.get("high", 0.0))
                lo = float(k.get("low", 0.0))
                vol = float(k.get("volume", 1.0))
                prev_cl = float(k.get("prev_close", cl))

                # Zero volume suspension
                if vol <= 0:
                    violations.append(f"Suspension execution violation on {t_date} for {code}: traded on 0 volume.")

                # One-word limit-up (open == high == low == close >= prev_close * 1.095)
                is_one_word_limit_up = (op == hi == lo == cl) and prev_cl > 0 and (cl >= prev_cl * 1.095)
                is_one_word_limit_down = (op == hi == lo == cl) and prev_cl > 0 and (cl <= prev_cl * 0.905)

                if action == "buy" and is_one_word_limit_up:
                    violations.append(f"Limit-up violation on {t_date} for {code}: bought on locked one-word limit-up.")
                if action == "sell" and is_one_word_limit_down:
                    violations.append(f"Limit-down violation on {t_date} for {code}: sold on locked one-word limit-down.")

        is_compliant = len(violations) == 0
        return is_compliant, violations


# ==============================================================================
# G2: 效能达标与过拟合门禁 (OverfittingGuard)
# ==============================================================================
class OverfittingGuard:
    """
    Overfitting, Statistical Significance & OOS Decay Guard.

    Implements:
    1. Out-of-Sample (OOS) performance decay verification.
    2. Marcos López de Prado's Deflated Sharpe Ratio (DSR) calibration.
    """

    @classmethod
    def calculate_oos_decay(
        cls,
        in_sample_metrics: Dict[str, Any],
        out_sample_metrics: Dict[str, Any],
        max_allowed_decay: float = 0.35,
    ) -> Tuple[bool, float, float, List[str]]:
        """
        Calculate performance retention and decay between In-Sample and Out-of-Sample.

        Returns:
            (is_acceptable, ret_decay_ratio, sharpe_decay_ratio, details)
        """
        is_ret = float(in_sample_metrics.get("annual_return_pct", in_sample_metrics.get("total_return_pct", 0.0)))
        oos_ret = float(out_sample_metrics.get("annual_return_pct", out_sample_metrics.get("total_return_pct", 0.0)))

        is_sr = float(in_sample_metrics.get("sharpe_ratio", 0.0))
        oos_sr = float(out_sample_metrics.get("sharpe_ratio", 0.0))

        details = []

        # Return decay: 1 - (oos / is)
        if is_ret > 0:
            ret_decay = 1.0 - (oos_ret / is_ret)
        else:
            ret_decay = 1.0 if oos_ret <= 0 else 0.0

        # Sharpe decay: 1 - (oos / is)
        if is_sr > 0:
            sr_decay = 1.0 - (oos_sr / is_sr)
        else:
            sr_decay = 1.0 if oos_sr <= 0 else 0.0

        details.append(f"In-Sample Return: {is_ret:.2f}%, OOS Return: {oos_ret:.2f}% (Decay: {ret_decay*100:.1f}%)")
        details.append(f"In-Sample Sharpe: {is_sr:.3f}, OOS Sharpe: {oos_sr:.3f} (Decay: {sr_decay*100:.1f}%)")

        is_acceptable = (sr_decay <= max_allowed_decay) and (oos_ret > 0)
        if not is_acceptable:
            details.append(
                f"OOS Sharpe decay ({sr_decay*100:.1f}%) exceeds safety threshold ({max_allowed_decay*100:.1f}%)"
            )

        return is_acceptable, ret_decay, sr_decay, details

    @classmethod
    def calculate_deflated_sharpe_ratio(
        cls,
        observed_sharpe: float,
        daily_returns: List[float],
        num_trials: int = 1,
        annualized: bool = True,
    ) -> Tuple[float, float, str]:
        """
        Calculate Deflated Sharpe Ratio (DSR) accounting for multiple testing,
        skewness, and fat tails (Marcos López de Prado, 2014).

        Returns:
            (dsr_probability, expected_max_sr, summary)
        """
        T = len(daily_returns)
        if T < 20:
            return 0.5, 0.0, "Sample size too small for statistical DSR calibration (requires T >= 20)"

        # Normalize daily returns
        mean_r = sum(daily_returns) / T
        var_r = sum((r - mean_r) ** 2 for r in daily_returns) / (T - 1)
        std_r = math.sqrt(var_r) if var_r > 0 else 1e-8

        # Skewness (gamma_3) & Kurtosis (gamma_4)
        skew = sum((r - mean_r) ** 3 for r in daily_returns) / (T * (std_r ** 3)) if std_r > 0 else 0.0
        kurt = sum((r - mean_r) ** 4 for r in daily_returns) / (T * (std_r ** 4)) if std_r > 0 else 3.0

        # Un-annualize Sharpe to sample frequency if observed was annualized
        sr = observed_sharpe / math.sqrt(250) if annualized else observed_sharpe

        # Expected maximum Sharpe under null hypothesis of N multiple trials
        gamma_euler = 0.5772156649015329
        n_trials = max(1, num_trials)
        if n_trials > 1:
            z_term = math.sqrt(2.0 * math.log(n_trials))
            expected_max_sr = (z_term - (math.log(math.pi) + math.log(math.log(n_trials))) / (2.0 * z_term)) / math.sqrt(250)
        else:
            expected_max_sr = 0.0

        # Asymptotic variance of Sharpe ratio: sigma_sr^2 = (1 - skew*sr + (kurt-1)/4 * sr^2) / (T - 1)
        var_sr = (1.0 - skew * sr + ((kurt - 1.0) / 4.0) * (sr ** 2)) / (T - 1)
        sigma_sr = math.sqrt(max(1e-9, var_sr))

        # Standardized Z-statistic
        z_stat = (sr - expected_max_sr) / sigma_sr

        # Normal CDF: Phi(Z)
        dsr_prob = 0.5 * (1.0 + math.erf(z_stat / math.sqrt(2.0)))

        summary = (
            f"DSR Confidence: {dsr_prob*100:.1f}% | Skewness: {skew:.2f}, Kurtosis: {kurt:.2f} | "
            f"Observed SR: {observed_sharpe:.2f}, Trials: {num_trials}"
        )
        return round(dsr_prob, 4), round(expected_max_sr * math.sqrt(250), 3), summary


# ==============================================================================
# G_Total: 综合质量门禁中枢 (AlgorithmQualityGate)
# ==============================================================================
class AlgorithmQualityGate:
    """
    Master Quality Gate Controller.

    Orchestrates G1 (Research compliance, Lookahead & A-Share rules) and
    G2 (Performance threshold, OOS decay & Overfitting testing).
    """

    @classmethod
    def audit_algorithm(
        cls,
        name_or_func: Any,
        sample_klines: Optional[List[Any]] = None,
        trade_log: Optional[List[Dict[str, Any]]] = None,
        klines_by_date: Optional[Dict[str, Dict[str, float]]] = None,
        in_sample_metrics: Optional[Dict[str, Any]] = None,
        out_sample_metrics: Optional[Dict[str, Any]] = None,
        daily_returns: Optional[List[float]] = None,
        num_trials: int = 1,
    ) -> QualityGateReport:
        """
        Run the complete suite of quality gate checks on an algorithm.
        """
        algo_name = name_or_func if isinstance(name_or_func, str) else getattr(name_or_func, "__name__", str(name_or_func))
        passed_checks = []
        warnings = []
        violations = []
        metrics = {}
        recommendations = []
        score = 100.0

        # ── 1. G1: Lookahead Static Audit ──────────────────────────────────────
        if callable(name_or_func):
            is_clean, ast_violations = LookaheadGuard.audit_source_code(name_or_func)
            if is_clean:
                passed_checks.append("G1.1 AST static analysis: no forward slicing detected.")
            else:
                for v in ast_violations:
                    violations.append(f"G1.1 Code Audit: {v}")
                score -= 30.0

            # Dynamic probe
            if sample_klines and len(sample_klines) >= 10:
                is_probe_ok, probe_msg = LookaheadGuard.probe_temporal_integrity(name_or_func, sample_klines)
                if is_probe_ok:
                    passed_checks.append(f"G1.1 Temporal Probe: {probe_msg}")
                else:
                    violations.append(f"G1.1 Temporal Probe: {probe_msg}")
                    score -= 40.0

        # ── 2. G1: A-Share Rules Audit ─────────────────────────────────────────
        if trade_log:
            is_trade_ok, trade_violations = AShareComplianceGuard.audit_trade_log(trade_log, klines_by_date)
            if is_trade_ok:
                passed_checks.append(f"G1.2 A-share rules: all {len(trade_log)} trades adhere to T+1 & limit constraints.")
            else:
                for tv in trade_violations:
                    violations.append(f"G1.2 Market Rules: {tv}")
                score -= min(40.0, len(trade_violations) * 15.0)

        # ── 3. G2: Performance & OOS Decay ─────────────────────────────────────
        if in_sample_metrics and out_sample_metrics:
            is_oos_ok, ret_decay, sr_decay, oos_details = OverfittingGuard.calculate_oos_decay(
                in_sample_metrics, out_sample_metrics
            )
            metrics["oos_ret_decay_pct"] = round(ret_decay * 100, 2)
            metrics["oos_sharpe_decay_pct"] = round(sr_decay * 100, 2)

            if is_oos_ok:
                passed_checks.append(f"G2.1 OOS Validation: Sharpe decay {sr_decay*100:.1f}% within 35% tolerance.")
            else:
                warnings.append(f"G2.1 OOS Validation: Sharpe decay {sr_decay*100:.1f}% exceeds tolerance.")
                recommendations.append("Reduce parameter degrees of freedom or introduce L2/volatility regularization.")
                score -= 20.0

        # ── 4. G2: Deflated Sharpe Ratio (DSR) ──────────────────────────────────
        if daily_returns and in_sample_metrics:
            obs_sr = float(in_sample_metrics.get("sharpe_ratio", 1.0))
            dsr_prob, exp_max_sr, dsr_summary = OverfittingGuard.calculate_deflated_sharpe_ratio(
                observed_sharpe=obs_sr,
                daily_returns=daily_returns,
                num_trials=num_trials,
            )
            metrics["dsr_confidence_pct"] = round(dsr_prob * 100, 2)
            metrics["expected_max_trial_sr"] = exp_max_sr

            if dsr_prob >= 0.80:
                passed_checks.append(f"G2.2 DSR Audit: {dsr_summary} (High Statistical Significance)")
            elif dsr_prob >= 0.50:
                warnings.append(f"G2.2 DSR Audit: Moderate confidence ({dsr_prob*100:.1f}%). May have trial selection bias.")
                score -= 10.0
            else:
                violations.append(f"G2.2 DSR Audit: Low confidence ({dsr_prob*100:.1f}%). High probability of overfitted false discovery.")
                recommendations.append("Increase out-of-sample test sample duration or decrease parameter search grids.")
                score -= 25.0

        # Score lower bound
        score = max(0.0, score)

        # Decision status
        if violations:
            status = QualityGateStatus.BLOCKED
        elif warnings or score < 80.0:
            status = QualityGateStatus.WARNING
        else:
            status = QualityGateStatus.PASSED

        return QualityGateReport(
            target_name=algo_name,
            status=status,
            score=score,
            passed_checks=passed_checks,
            warnings=warnings,
            violations=violations,
            metrics=metrics,
            recommendations=recommendations,
        )
